name = "Kombinator"
uuid = "c77a6b6f-abe2-4dd7-b2b3-8d5a1483deca"
authors = ["Thibaut Cuvelier <cuvelier.thibaut@gmail.com> and contributors"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
JuMP = "^0.21, ^0.22"
LightGraphs = "^1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
